query GetAllNavItems {
  navigations(first: 1) {
    id
    linkTo {
      __typename
      ... on Page {
        title
        slug
      }
      ... on Chapter {
        title
        slug
        pages {
          title
          slug
        }
      }
      ... on ExternalLink {
        label
        url
      }
    }
  }
}
