query GetAllNavItems {
  navItems {
    id
    linkTo {
      __typename
      ... on Page {
        title
        slug
      }
      ... on Chapter {
        title
        slug
        pages {
          title
          slug
        }
      }
    }
  }
}
